# Generated by Django 4.2 on 2025-01-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название блюда')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='начало смены')),
                ('end_time', models.DateTimeField(verbose_name='окончание смены')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='общая выручка')),
                ('total_orders', models.PositiveIntegerField(verbose_name='общее количество заказов')),
            ],
            options={
                'verbose_name': 'смена',
                'verbose_name_plural': 'смены',
            },
        ),
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(verbose_name='общая стоимость')),
                ('table_number', models.PositiveSmallIntegerField(verbose_name='номер стола')),
                ('status', models.CharField(choices=[('padding', 'ожидает'), ('ready', 'готово'), ('paid', 'оплачен')], default='padding', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='oders_app.dish', verbose_name='блюда')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
