# Generated by Django 4.2 on 2025-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oders_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='общая стоимость')),
                ('status', models.CharField(choices=[('padding', 'ожидает'), ('ready', 'готово'), ('paid', 'оплачен')], default='padding', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(to='oders_app.dish', verbose_name='блюда')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='номер стола')),
            ],
            options={
                'verbose_name': 'стол',
                'verbose_name_plural': 'столы',
            },
        ),
        migrations.RemoveField(
            model_name='shift',
            name='total_orders',
        ),
        migrations.DeleteModel(
            name='Oder',
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.ManyToManyField(to='oders_app.table', verbose_name='номер стола'),
        ),
    ]
