# Generated by Django 4.2 on 2025-01-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oders_app', '0002_order_table_remove_shift_total_orders_delete_oder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AddField(
            model_name='table',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='свободен'),
        ),
    ]
