# Generated by Django 4.2 on 2025-01-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oders_app', '0003_table_is_active_table_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_number',
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oders_app.table', verbose_name='номер стола'),
        ),
    ]
