# Generated by Django 4.2 on 2025-01-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oders_app', '0004_remove_order_table_number_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
