# Generated by Django 4.2 on 2025-01-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oders_app', '0005_alter_dish_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='description',
        ),
    ]
