# Generated by Django 4.2 on 2025-01-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oders_app', '0007_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='окончание смены'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='начало смены'),
        ),
    ]
